// Generates the fake backend's content fixture from supabase/seed.sql.
//
// Usage (from app/):
//   dart run tool/seed_to_fixture.dart
//
// test/tool/seed_fixture_test.dart fails when the fixture drifts from the
// seed, so rerun this after editing the seed.
import 'dart:io';

import 'package:flui/features/exercises/domain/cloze_exercise.dart';
import 'package:flui/features/reading/domain/reading.dart';
import 'package:flui/features/vocabulary/domain/word.dart';

import 'seed/seed_parser.dart';

const _seedPath = '../supabase/seed.sql';
const _outputPath = 'lib/features/vocabulary/data/fake/seed_content.dart';

Future<void> main() async {
  final words = parseSeedWords(File(_seedPath).readAsStringSync());
  final buffer = StringBuffer()
    ..writeln(
      '// GENERATED by tool/seed_to_fixture.dart from '
      'supabase/seed.sql. Do not edit.',
    )
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln(
      "import 'package:flui/features/exercises/domain/cloze_exercise.dart';",
    )
    ..writeln("import 'package:flui/features/reading/domain/reading.dart';")
    ..writeln("import 'package:flui/features/vocabulary/domain/word.dart';")
    ..writeln()
    ..writeln('/// The starter words of the seed (AI-drafted, pending review).')
    ..writeln('const seedWords = <Word>[');
  for (final word in words) {
    buffer.writeln('${_word(word)},');
  }
  buffer.writeln('];');

  File(_outputPath).writeAsStringSync(buffer.toString());
  final format = await Process.run('dart', ['format', _outputPath]);
  stdout.writeln('Wrote ${words.length} words to $_outputPath');
  if (format.exitCode != 0) stderr.writeln(format.stderr);
}

String _s(String? value) {
  if (value == null) return 'null';
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n');
  return "'$escaped'";
}

String _list(Iterable<String> items) => '[${items.join(', ')}]';

/// `name: 'value', ` or nothing for null (avoids redundant null arguments).
String _opt(String name, String? value) =>
    value == null ? '' : '$name: ${_s(value)}, ';

String _word(Word w) =>
    '''
Word(
  id: ${_s(w.id)},
  slug: ${_s(w.slug)},
  lemma: ${_s(w.lemma)},
  partOfSpeech: PartOfSpeech.${w.partOfSpeech.name},
  syllables: ${_list(w.syllables.map(_s))},
  stressedSyllable: ${w.stressedSyllable},
  ${_opt('ipaLatam', w.ipaLatam)}${_opt('ipaEs', w.ipaEs)}
  explanation: ${_s(w.explanation)},
  exampleSentence: ${_s(w.exampleSentence)},
  register: WordRegister.${w.register.name},
  pedantryRisk: ${w.pedantryRisk},
  ${_opt('usageTip', w.usageTip)}${_opt('whenNotToUse', w.whenNotToUse)}
  collocations: ${_list(w.collocations.map(_s))},
  replaces: ${_list(w.replaces.map(_replacement))},
  family: ${_list(w.family.map(_s))},
  sortOrder: ${w.sortOrder},
  confusions: ${_list(w.confusions.map(_confusion))},
  exercises: ${_list(w.exercises.map(_exercise))},
  readings: ${_list(w.readings.map(_reading))},
)''';

String _replacement(Replacement r) =>
    'Replacement(before: ${_s(r.before)}, after: ${_s(r.after)})';

String _confusion(WordConfusion c) =>
    'WordConfusion(id: ${_s(c.id)}, wordId: ${_s(c.wordId)}, '
    'confusedWith: ${_s(c.confusedWith)}, '
    '${_opt('confusedWordId', c.confusedWordId)}'
    'difference: ${_s(c.difference)}, '
    '${_opt('memoryTrick', c.memoryTrick)})';

String _exercise(ClozeExercise e) =>
    'ClozeExercise(id: ${_s(e.id)}, wordId: ${_s(e.wordId)}, '
    'sentence: ${_s(e.sentence)}, hintGeneral: ${_s(e.hintGeneral)}, '
    'explanation: ${_s(e.explanation)}, position: ${e.position}, '
    'options: ${_list(e.options.map(_option))},)';

String _option(ExerciseOption o) =>
    'ExerciseOption(id: ${_s(o.id)}, text: ${_s(o.text)}, '
    'isCorrect: ${o.isCorrect}, position: ${o.position}, '
    '${_distractor(o.distractorType)}'
    '${_opt('whyNot', o.whyNot)}${_opt('hintSpecific', o.hintSpecific)})';

String _distractor(DistractorType? type) =>
    type == null ? '' : 'distractorType: DistractorType.${type.name}, ';

String _reading(Reading r) =>
    'Reading(id: ${_s(r.id)}, wordId: ${_s(r.wordId)}, '
    'scene: Scene.${r.scene.name}, '
    'conversationType: ConversationType.${r.conversationType.name}, '
    'title: ${_s(r.title)}, body: ${_s(r.body)}, '
    'beforePhrase: ${_s(r.beforePhrase)}, afterPhrase: ${_s(r.afterPhrase)}, '
    'position: ${r.position},)';
