// Generates the fake backend's content fixture from supabase/seed.sql.
//
// Usage (from app/):
//   dart run tool/seed_to_fixture.dart
//
// test/tool/seed_fixture_test.dart fails when the fixture drifts from the
// seed, so rerun this after editing the seed.
import 'dart:io';

import 'package:flui/features/reading/domain/reading.dart';
import 'package:flui/features/vocabulary/domain/exercises/cloze_exercise.dart';
import 'package:flui/features/vocabulary/domain/word.dart';

import 'seed/seed_parser.dart';

const _seedPath = '../supabase/seed.sql';
const _outputPath = 'lib/features/vocabulary/data/fake/seed_content.dart';

Future<void> main() async {
  final sql = File(_seedPath).readAsStringSync();
  final words = parseSeedWords(sql);

  File(_outputPath).writeAsStringSync(
    renderSeedFixture(words, themeSlugs: parseSeedWordThemeSlugs(sql)),
  );
  final format = await Process.run('dart', ['format', _outputPath]);
  stdout.writeln('Wrote ${words.length} words to $_outputPath');
  if (format.exitCode != 0) stderr.writeln(format.stderr);
}

/// The unformatted fixture source for [words].
///
/// Extracted so tool/seed_fixture_check.dart can render the same bytes from a
/// different seed file without duplicating the renderer.
String renderSeedFixture(
  List<Word> words, {
  Map<String, List<String>> themeSlugs = const {},
}) {
  final buffer = StringBuffer()
    ..writeln(
      '// GENERATED by tool/seed_to_fixture.dart from '
      'supabase/seed.sql. Do not edit.',
    )
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln(
      "import 'package:flui/features/vocabulary/domain/exercises/cloze_exercise.dart';",
    )
    ..writeln("import 'package:flui/features/reading/domain/reading.dart';")
    ..writeln("import 'package:flui/features/vocabulary/domain/word.dart';")
    ..writeln()
    ..writeln('/// The starter words of the seed (AI-drafted, pending review).')
    ..writeln('const seedWords = <Word>[');
  for (final word in words) {
    buffer.writeln('${_word(word)},');
  }
  buffer
    ..writeln('];')
    ..writeln()
    ..writeln('/// Word slug to the theme slugs of `public.word_themes`.')
    ..writeln('///')
    ..writeln('/// The theme *taxonomy* is still hand-written in')
    ..writeln('/// features/themes/data/fake/seed_themes.dart; only the links')
    ..writeln('/// are generated, because content:emit is what writes them.')
    ..writeln('const seedWordThemeSlugs = <String, List<String>>{');
  for (final word in words) {
    final slugs = themeSlugs[word.slug] ?? const <String>[];
    if (slugs.isEmpty) continue;
    buffer.writeln('  ${_s(word.slug)}: ${_list(slugs.map(_s))},');
  }
  buffer.writeln('};');
  return buffer.toString();
}

String _s(String? value) {
  if (value == null) return 'null';
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n');
  return "'$escaped'";
}

String _list(Iterable<String> items) => '[${items.join(', ')}]';

/// `name: 'value', ` or nothing for null (avoids redundant null arguments).
String _opt(String name, String? value) =>
    value == null ? '' : '$name: ${_s(value)}, ';

/// `name: [...],` or nothing when the list is empty.
///
/// Every list field of [Word] defaults to `const []`, so spelling an empty one
/// out is a redundant argument — and `dart analyze --fatal-infos` runs over
/// this generated file like any other.
String _optList(String name, Iterable<String> items) =>
    items.isEmpty ? '' : '$name: ${_list(items)},';

String _word(Word w) =>
    '''
Word(
  id: ${_s(w.id)},
  slug: ${_s(w.slug)},
  lemma: ${_s(w.lemma)},
  partOfSpeech: PartOfSpeech.${w.partOfSpeech.name},
  syllables: ${_list(w.syllables.map(_s))},
  stressedSyllable: ${w.stressedSyllable},
  ${_opt('ipaLatam', w.ipaLatam)}${_opt('ipaEs', w.ipaEs)}
  explanation: ${_s(w.explanation)},
  exampleSentence: ${_s(w.exampleSentence)},
  register: WordRegister.${w.register.name},
  pedantryRisk: ${w.pedantryRisk},
  ${_opt('usageTip', w.usageTip)}${_opt('whenNotToUse', w.whenNotToUse)}
  ${_optList('collocations', w.collocations.map(_s))}
  ${_optList('replaces', w.replaces.map(_replacement))}
  ${_optList('family', w.family.map(_s))}
  sortOrder: ${w.sortOrder},
  ${_optList('confusions', w.confusions.map(_confusion))}
  ${_optList('exercises', w.exercises.map(_exercise))}
  ${_optList('readings', w.readings.map(_reading))}
)''';

String _replacement(Replacement r) =>
    'Replacement(before: ${_s(r.before)}, after: ${_s(r.after)})';

String _confusion(WordConfusion c) =>
    'WordConfusion(id: ${_s(c.id)}, wordId: ${_s(c.wordId)}, '
    'confusedWith: ${_s(c.confusedWith)}, '
    '${_opt('confusedWordId', c.confusedWordId)}'
    'difference: ${_s(c.difference)}, '
    '${_opt('memoryTrick', c.memoryTrick)})';

String _exercise(ClozeExercise e) =>
    'ClozeExercise(id: ${_s(e.id)}, wordId: ${_s(e.wordId)}, '
    'sentence: ${_s(e.sentence)}, hintGeneral: ${_s(e.hintGeneral)}, '
    'explanation: ${_s(e.explanation)}, position: ${e.position}, '
    'options: ${_list(e.options.map(_option))},)';

String _option(ExerciseOption o) =>
    'ExerciseOption(id: ${_s(o.id)}, text: ${_s(o.text)}, '
    'isCorrect: ${o.isCorrect}, position: ${o.position}, '
    '${_distractor(o.distractorType)}'
    '${_opt('whyNot', o.whyNot)}${_opt('hintSpecific', o.hintSpecific)})';

String _distractor(DistractorType? type) =>
    type == null ? '' : 'distractorType: DistractorType.${type.name}, ';

String _reading(Reading r) =>
    'Reading(id: ${_s(r.id)}, wordId: ${_s(r.wordId)}, '
    'scene: Scene.${r.scene.name}, '
    'conversationType: ConversationType.${r.conversationType.name}, '
    'title: ${_s(r.title)}, body: ${_s(r.body)}, '
    'beforePhrase: ${_s(r.beforePhrase)}, afterPhrase: ${_s(r.afterPhrase)}, '
    'position: ${r.position},)';
